version: '3.3'
services:

  mongo:
    image: 'mongo:8.0'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: traveloka_scrap
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
